name: Release

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build BBCF_IM
        run: msbuild BBCF_IM.sln -property:Configuration=Release
      
      - name: Calculate checksums
        working-directory: ${{ github.workspace }}\bin\Release\
        run: |
          $(CertUtil -hashfile dinput8.dll MD5)[1] -replace " ","" > dinput8.dll.md5
          $(CertUtil -hashfile dinput8.dll SHA256)[1] -replace " ","" > dinput8.dll.sha256

      # action-gh-release has issues with back slashes in file paths
      # working-directory is also not supported
      # see issue https://github.com/softprops/action-gh-release/issues/280
      # for now, just use "." instead of "${{ github.workspace }}" and
      # use forward slashes
      - name: Release BBCF_IM
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/Release/dinput8.dll
            ./bin/Release/dinput8.dll.md5
            ./bin/Release/dinput8.dll.sha256
            ./bin/Release/settings.ini
            ./bin/Release/palettes.ini
